/** Preload: stellt eine typisierte, minimale API sicher über contextBridge bereit. */

import { contextBridge, ipcRenderer, webUtils } from "electron";

import type { GobdeskApi } from "../shared/api.js";

const api: GobdeskApi = {
  getSettings: () => ipcRenderer.invoke("settings:get"),
  updateSettings: (input) => ipcRenderer.invoke("settings:update", input),
  listCustomers: () => ipcRenderer.invoke("customers:list"),
  listCustomersDetailed: (search) => ipcRenderer.invoke("customers:listDetailed", search),
  getCustomer: (id) => ipcRenderer.invoke("customers:get", id),
  createCustomer: (input) => ipcRenderer.invoke("customers:create", input),
  updateCustomer: (id, input) => ipcRenderer.invoke("customers:update", id, input),
  listTaxRates: () => ipcRenderer.invoke("tax:list"),
  listInvoices: (filter) => ipcRenderer.invoke("invoices:list", filter),
  createDraftInvoice: (input) => ipcRenderer.invoke("invoices:createDraft", input),
  updateDraftInvoice: (id, input) => ipcRenderer.invoke("invoices:updateDraft", id, input),
  issueInvoice: (id) => ipcRenderer.invoke("invoices:issue", id),
  cancelInvoice: (id, reason) => ipcRenderer.invoke("invoices:cancel", id, reason),
  previewInvoice: (input) => ipcRenderer.invoke("invoices:preview", input),
  validateInvoice: (id) => ipcRenderer.invoke("invoices:validate", id),
  getInvoice: (id) => ipcRenderer.invoke("invoices:get", id),
  markInvoicePaid: (id) => ipcRenderer.invoke("invoices:markPaid", id),
  listOverdueInvoices: () => ipcRenderer.invoke("dunning:list"),
  exportDunning: (invoiceId, level, feeCents) =>
    ipcRenderer.invoke("dunning:export", invoiceId, level, feeCents),
  addPayment: (invoiceId, paidAt, amountCents, note) =>
    ipcRenderer.invoke("payments:add", invoiceId, paidAt, amountCents, note),
  deletePayment: (paymentId) => ipcRenderer.invoke("payments:delete", paymentId),
  openArtifact: (invoiceId, kind) => ipcRenderer.invoke("artifact:open", invoiceId, kind),
  listEuerCategories: () => ipcRenderer.invoke("euer:categories"),
  createExpense: (input) => ipcRenderer.invoke("expenses:create", input),
  getExpense: (id) => ipcRenderer.invoke("expenses:get", id),
  updateExpense: (id, input) => ipcRenderer.invoke("expenses:update", id, input),
  listExpenses: (year) => ipcRenderer.invoke("expenses:list", year),
  listIncomeCategories: () => ipcRenderer.invoke("income:categories"),
  createOtherIncome: (input) => ipcRenderer.invoke("income:create", input),
  getOtherIncome: (id) => ipcRenderer.invoke("income:get", id),
  updateOtherIncome: (id, input) => ipcRenderer.invoke("income:update", id, input),
  listOtherIncome: (year) => ipcRenderer.invoke("income:list", year),
  euerReport: (year) => ipcRenderer.invoke("euer:report", year),
  listEuerYears: () => ipcRenderer.invoke("euer:years"),
  runDemoInvoice: () => ipcRenderer.invoke("invoices:runDemo"),
  gobdReport: () => ipcRenderer.invoke("gobd:report"),
  gobdQuickCheck: () => ipcRenderer.invoke("gobd:quick"),
  listJournal: () => ipcRenderer.invoke("journal:list"),
  listJournalForInvoice: (invoiceId) => ipcRenderer.invoke("journal:forInvoice", invoiceId),
  exportJournal: () => ipcRenderer.invoke("journal:export"),
  exportZ3: () => ipcRenderer.invoke("gobd:exportZ3"),
  getVerfdokTexts: () => ipcRenderer.invoke("verfdok:getTexts"),
  exportVerfahrensdok: (format, texts) => ipcRenderer.invoke("verfdok:export", format, texts),
  getStorageInfo: () => ipcRenderer.invoke("config:get"),
  openDataDir: () => ipcRenderer.invoke("config:openDataDir"),
  changeDataDir: () => ipcRenderer.invoke("config:changeDataDir"),
  createBackup: () => ipcRenderer.invoke("backup:create"),
  importDocuments: () => ipcRenderer.invoke("documents:import"),
  importDocumentPaths: (paths) => ipcRenderer.invoke("documents:importPaths", paths),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  listDocuments: (filter) => ipcRenderer.invoke("documents:list", filter),
  getDocument: (id) => ipcRenderer.invoke("documents:get", id),
  updateDocument: (id, input) => ipcRenderer.invoke("documents:update", id, input),
  updateDocumentOcr: (id, text) => ipcRenderer.invoke("documents:updateOcr", id, text),
  archiveDocument: (id, archived) => ipcRenderer.invoke("documents:archive", id, archived),
  deleteDocument: (id) => ipcRenderer.invoke("documents:delete", id),
  openDocument: (id) => ipcRenderer.invoke("documents:open", id),
  listDocumentTypes: () => ipcRenderer.invoke("documents:types"),
  listTags: () => ipcRenderer.invoke("documents:tags"),
  linkDocument: (documentId, targetType, targetId) =>
    ipcRenderer.invoke("documents:link", documentId, targetType, targetId),
  unlinkDocument: (linkId) => ipcRenderer.invoke("documents:unlink", linkId),
  listLinkTargets: () => ipcRenderer.invoke("documents:linkTargets"),
  listDocumentsForTarget: (targetType, targetId) =>
    ipcRenderer.invoke("documents:forTarget", targetType, targetId),
  listOrders: (filter) => ipcRenderer.invoke("orders:list", filter),
  getOrder: (id) => ipcRenderer.invoke("orders:get", id),
  createOrder: (input) => ipcRenderer.invoke("orders:create", input),
  updateOrder: (id, input) => ipcRenderer.invoke("orders:update", id, input),
  deleteOrder: (id) => ipcRenderer.invoke("orders:delete", id),
  listOrderOptions: () => ipcRenderer.invoke("orders:options"),
  suggestOrderNumber: () => ipcRenderer.invoke("orders:suggestNumber"),
  importDocumentsForOrder: (orderId) => ipcRenderer.invoke("documents:importForOrder", orderId),
  getAppInfo: () => ipcRenderer.invoke("app:info"),
  checkForUpdate: () => ipcRenderer.invoke("app:checkUpdate"),
  openExternal: (url) => ipcRenderer.invoke("app:openExternal", url),
};

contextBridge.exposeInMainWorld("gobdesk", api);
